---
title: "Introducción Proyecto"
format: html
editor: visual
editor_options: 
chunk_output_type: console
---

# INTRODUCCIÓN

La Organización Mundial de la Salud (OMS) considera a la obesidad y obesidad morbida 
como una epidemia de una enfermedad crónica no transmisible. En general, estas dos, sumadas al sobrepeso, corresponden a enfermedades que se caracterizan por un exceso o una acumulación excesiva y general de grasa en el cuerpo. Esto puede ser medido mediante el Índice de masa corporal (IMC) que, mediante una fórmula matemática en la que participa la talla y peso de una persona, entrega el porcentaje total de masa grasa del cuerpo, siendo 18.5 - 24.9% el rango óptimo y sobre 30% obesidad. La causa más común de un aumento del IMC es la ingesta de más calorías de las que se queman durante el ejercicio y las actividades diarias normales, pero además podrían influir otros factores, como la presencia de otras enfermedades, la ingesta de algunos medicamentos que propician el aumento de peso, aspectos genéticos y sociales, entre otros.

En sus esencias, estas enfermedades no implican un riesgo en el ser humano, pero son las enfermedades secundarias derivadas de estas, como la diabetes, hipertensión, hepatitis, entre otras, la que sí implican un riesgo inminente en el ser humano.

El sobrepeso, obesidad y obesidad morbida son un problema de salud pública que ha afectado a todos los países del mundo sin importar su desarrollo. En Chile, se estima que el 75% de la población tiene, como estado nutricional alguna de estas 3 condiciones. Esto posiciona al país latinoamericano como segundo en el ranking mundial de países con mayor índice de estas enfermedades en su población. Estos alarmantes datos dan paso para cuestionar las razones que hay detrás de este alto porcentaje y así poder crear un plan de acción para poder disminuir la cantidad de gente afectada. En particular, para poder crear políticas públicas que influyan en toda la población, es necesario observar e informarse sobre cómo se comporta esta en función de los factores sociales que afectan y propician el aumento del IMC en las personas y, en consecuencia, al desarrollo de las enfermedades en cuestión. 

El objetivo de este informe es visualizar, evidenciar e informar cómo afectan, al estado nutricional de las personas Chilenas, algunos factores sociales, como el nivel socio económico, acceso a alimentos saludables, sistema previsional, edad, sexo, entre otros. Para lograr este objetivo se realizará un análisis exploratorio de los resultados de la encuesta  de Caracterización Socioeconómica Nacional (CASEN)  realizada el año 2020 que tiene como objetivo principal estimar la magnitud de la pobreza en Chile. Dado que esta encuesta es extensa, se utilizarán solo algunas secciones relevantes como la de salud e ingresos, entre otras. 

Este informe se dividirá en 4 instancias. En primer lugar, se mostrará un resumen de la encuesta CASEN, y las preguntas utilizadas para este informe. Luego, comenzarán a visualizar y estudiar resultados de algunos factores demográficos como el sexo, edad y región. En tercer lugar, se estudiarán factores sociales como los ingresos familiares, cantidad de personas por vivienda, acceso a alimentos saludables, entre otros. Por último se realizará una conclusión de todos los estudios de las secciones anteriores. 




